HealthCareWebApp/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HealthCareWebApp;
using HealthCareWebApp.Models;
using Microsoft.CodeAnalysis;

namespace HealthCareWebApp.Controllers
{
    public class DoctorsController : Controller
    {
        private readonly HealthCareWebAppContext _context;

        public DoctorsController(HealthCareWebAppContext context)
        {
            _context = context;
        }

        // GET: Doctors
        public async Task<IActionResult> Index(string? name, string? specialty, string? location)
        {
            if (specialty == null && name==null && location==null)
            {            
            return _context.Doctor != null ? 
                          View(await _context.Doctor.ToListAsync()) :
                          Problem("Entity set 'HealthCareWebAppContext.Doctor'  is null.");
            }

            var doctors = _context.Doctor.AsQueryable();

            if (!string.IsNullOrEmpty(name))
            {
                doctors = doctors.Where(d => d.Name.Contains(name));
            }

            if (!string.IsNullOrEmpty(specialty))
            {
                doctors = doctors.Where(d => d.Specialty.Contains(specialty));
            }

            if (!string.IsNullOrEmpty(location))
            {
                doctors = doctors.Where(d => d.Location.Contains(location));
            }

            var results = await doctors.ToListAsync();

            return View(results);
        }

        // GET: Doctors/Details/5


        //ACCEPT ONLY INTEGER
        [Route("Doctors/Details/{id:int}")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Doctor == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctor
                .FirstOrDefaultAsync(m => m.Id == id);
            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }

        // GET: Doctors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Doctors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Specialty,ContactInfo,Location")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(doctor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(doctor);
        }

        // GET: Doctors/Edit/5
      
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Doctor == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctor.FindAsync(id);
            if (doctor == null)
            {
                return NotFound();
            }
            return View(doctor);
        }

        // POST: Doctors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Specialty,ContactInfo")] Doctor doctor)
        {
            if (id != doctor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(doctor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DoctorExists(doctor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(doctor);
        }

        // GET: Doctors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Doctor == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctor
                .FirstOrDefaultAsync(m => m.Id == id);
            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }

        // POST: Doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Doctor == null)
            {
                return Problem("Entity set 'HealthCareWebAppContext.Doctor'  is null.");
            }
            var doctor = await _context.Doctor.FindAsync(id);
            if (doctor != null)
            {
                _context.Doctor.Remove(doctor);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        private bool DoctorExists(int id)
        {
          return (_context.Doctor?.Any(e => e.Id == id)).GetValueOrDefault();
        }



       
       



    }
}

HealthCareWebApp/Controllers/HomeController.cs
using HealthCareWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HealthCareWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HealthCareWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<html>
<head>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <title>Welcome to Our Hospital</title>

    <style>
        body {
            background-image: url('image.jpg');
            font-family: "Open Sans", sans-serif;
        }

        .hero-container {
            background-size: cover;
            background-position: center;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            text-align: center;
        }

            .hero-container h1 {
                font-size: 6rem;
                margin-bottom: 2rem;
                /* color: white;

                                        text-shadow: 2px 2px #0095ff;*/
            }

            .hero-container p {
                font-size: 2rem;
                margin-bottom: 2rem;
                /* color: white;

                                        text-shadow: 2px 2px #0095ff; */
            }

            .hero-container button {
                font-size: 1.5rem;
                padding: 1rem 2rem;
                background-color: #007bff;
                color: #fff;
                border: none;
                border-radius: 5px;
                transition: all 0.3s ease-in-out;
            }

            .hero-container button a{
                text-decoration: none;
                color: white;
            }
                .hero-container button:hover {
                    background-color: #0062cc;
                    cursor: pointer;
                }
    </style>
</head>
<body>
    <div class="hero-container">

        <h1 class="mb-4 text-3xl font-extrabold text-gray-900 dark:text-white md:text-5xl lg:text-6xl"><span class="text-transparent bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">Your Health,</span> Our Priority.</h1>

        <p>We provide the best medical services for you and your family.</p>
        <button style="text-decoration: none; color: white;">
            <a asp-area="" asp-controller="Doctors" asp-action="Index">Start Here</a>
        </button>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script>

</body>
</html>